name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
      - name: Build
        run: mvn -q -DskipTests package
      - name: Upload plugin jar
        uses: actions/upload-artifact@v4
        with:
          name: text-gateway.metabase-driver.jar
          path: target/text-gateway.metabase-driver.jar
